# Generated by scripts/generate_sync.py from sympheny_toolbox/_async/__init__.py — do not edit by hand.
"""Sympheny API client package (synchronous variant)."""

from sympheny_toolbox._sync.client import Sympheny


__all__ = ["Sympheny"]
