# Generated by scripts/generate_sync.py from sympheny_toolbox/_async/client.py — do not edit by hand.
"""The Sympheny API client (synchronous)."""

from __future__ import annotations

from typing import TYPE_CHECKING

from sympheny_toolbox._sync._transport import DEFAULT_BASE_URL, DEV_BASE_URL, Transport
from sympheny_toolbox._sync.analyses import Analyses
from sympheny_toolbox._sync.conversion_technologies import ConversionTechnologies
from sympheny_toolbox._sync.energy_carriers import EnergyCarriers
from sympheny_toolbox._sync.energy_demands import EnergyDemands
from sympheny_toolbox._sync.hubs import Hubs
from sympheny_toolbox._sync.impex import Impex
from sympheny_toolbox._sync.intra_hub_network_links import IntraHubNetworkLinks
from sympheny_toolbox._sync.network_links import NetworkLinks
from sympheny_toolbox._sync.network_technologies import NetworkTechnologies
from sympheny_toolbox._sync.profiles import Profiles
from sympheny_toolbox._sync.projects import Projects
from sympheny_toolbox._sync.scenarios import Scenarios
from sympheny_toolbox._sync.solar_resources import SolarResources
from sympheny_toolbox._sync.solver_jobs import SolverJobs
from sympheny_toolbox._sync.stages import Stages
from sympheny_toolbox._sync.storage_technologies import StorageTechnologies
from sympheny_toolbox._sync.technology_packages import TechnologyPackages
from sympheny_toolbox._sync.users import Users


if TYPE_CHECKING:
    from types import TracebackType


class Sympheny:
    """Sympheny API client (synchronous variant).

    Authenticates with email/password credentials against the Sympheny API and
    exposes the documented endpoints as typed resource groups, e.g.
    ``client.projects.list()``.

    Args:
        username: Sympheny account email address.
        password: Sympheny account password.
        is_dev: Use the development environment instead of production.
        base_url: Override the API base URL entirely (takes precedence over ``is_dev``).
        timeout: Request timeout in seconds.
    """

    def __init__(
        self,
        username: str,
        password: str,
        *,
        is_dev: bool = False,
        base_url: str | None = None,
        timeout: float = 30.0,
    ) -> None:
        if base_url is None:
            base_url = DEV_BASE_URL if is_dev else DEFAULT_BASE_URL
        self.is_dev = is_dev
        self._transport = Transport(username, password, base_url=base_url, timeout=timeout)

        self.projects = Projects(self._transport)
        self.analyses = Analyses(self._transport)
        self.scenarios = Scenarios(self._transport)
        self.stages = Stages(self._transport)
        self.hubs = Hubs(self._transport)
        self.energy_carriers = EnergyCarriers(self._transport)
        self.impex = Impex(self._transport)
        self.profiles = Profiles(self._transport)
        self.energy_demands = EnergyDemands(self._transport)
        self.solar_resources = SolarResources(self._transport)
        self.conversion_technologies = ConversionTechnologies(self._transport)
        self.storage_technologies = StorageTechnologies(self._transport)
        self.technology_packages = TechnologyPackages(self._transport)
        self.network_technologies = NetworkTechnologies(self._transport)
        self.network_links = NetworkLinks(self._transport)
        self.intra_hub_network_links = IntraHubNetworkLinks(self._transport)
        self.solver_jobs = SolverJobs(self._transport)
        self.users = Users(self._transport)

    @property
    def base_url(self) -> str:
        """The API base URL this client talks to."""
        return self._transport.base_url

    def close(self) -> None:
        """Close the underlying HTTP connection pool."""
        self._transport.close()

    def __enter__(self) -> Sympheny:
        return self

    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: TracebackType | None) -> None:
        self.close()
