# Generated by scripts/generate_sync.py from sympheny_toolbox/_async/hubs.py — do not edit by hand.
"""Operations on hubs of the Sympheny platform API (``hub-controller``)."""

from __future__ import annotations

from typing import TYPE_CHECKING

from sympheny_toolbox._envelope import dump, unwrap
from sympheny_toolbox.models import (
    HubRequestDto,
    HubRequestDtoPUT,
    HubResponseDto,
    ResponseDtoHubResponseDto,
    ResponseDtoListFHubResponseDto,
    ResponseDtoListHubResponseDto,
)


if TYPE_CHECKING:
    import builtins

    from sympheny_toolbox._sync._transport import Transport


class Hubs:
    """Operations on hubs (``hub-controller``)."""

    def __init__(self, transport: Transport) -> None:
        self._t = transport

    def list(self, scenario_guid: str) -> list[HubResponseDto]:
        """List the hubs of a scenario. ``GET /sympheny-app/scenarios/{scenarioGuid}/hubs``"""
        raw = self._t.request_json("GET", f"/sympheny-app/scenarios/{scenario_guid}/hubs")
        envelope = ResponseDtoListFHubResponseDto.model_validate(raw)
        return unwrap(envelope.data)

    def create(self, scenario_guid: str, request: HubRequestDto) -> HubResponseDto:
        """Create a new hub in a scenario. ``POST /sympheny-app/scenarios/{scenarioGuid}/hubs``"""
        raw = self._t.request_json("POST", f"/sympheny-app/scenarios/{scenario_guid}/hubs", json=dump(request))
        envelope = ResponseDtoHubResponseDto.model_validate(raw)
        return unwrap(envelope.data)

    def get(self, hub_guid: str) -> HubResponseDto:
        """Get hub details. ``GET /sympheny-app/scenarios/hubs/{guid}``"""
        raw = self._t.request_json("GET", f"/sympheny-app/scenarios/hubs/{hub_guid}")
        envelope = ResponseDtoHubResponseDto.model_validate(raw)
        return unwrap(envelope.data)

    def update(self, hub_guid: str, request: HubRequestDtoPUT) -> HubResponseDto:
        """Update a hub. ``PUT /sympheny-app/v2/scenarios/hubs/{guid}``"""
        raw = self._t.request_json("PUT", f"/sympheny-app/v2/scenarios/hubs/{hub_guid}", json=dump(request))
        envelope = ResponseDtoHubResponseDto.model_validate(raw)
        return unwrap(envelope.data)

    def delete(self, hub_guid: str) -> builtins.list[HubResponseDto]:
        """Delete a hub; returns the remaining hubs. ``DELETE /sympheny-app/scenarios/hubs/{guid}``"""
        raw = self._t.request_json("DELETE", f"/sympheny-app/scenarios/hubs/{hub_guid}")
        envelope = ResponseDtoListHubResponseDto.model_validate(raw)
        return unwrap(envelope.data)
