# Generated by scripts/generate_sync.py from sympheny_toolbox/_async/profiles.py — do not edit by hand.
"""Operations on profiles of the Sympheny platform API (``profile-controller``)."""

from __future__ import annotations

from typing import TYPE_CHECKING

from sympheny_toolbox._envelope import dump, unwrap
from sympheny_toolbox.models import (
    ProfileDetailsResponseDto,
    ProfileJsonRequestDto,
    ProfileRequestDtoPUT,
    ProfileResponseDto,
    ResponseDtoListProfileResponseDto,
    ResponseDtoProfileDetailsResponseDto,
    ResponseDtoProfileResponseDto,
)


if TYPE_CHECKING:
    from sympheny_toolbox._sync._transport import Transport


class Profiles:
    """Operations on profiles (``profile-controller``)."""

    def __init__(self, transport: Transport) -> None:
        self._t = transport

    def create(self, scenario_guid: str, request: ProfileJsonRequestDto) -> ProfileResponseDto:
        """Create a new profile in a scenario. ``POST /sympheny-app/scenarios/{scenarioGuid}/profiles-json``"""
        raw = self._t.request_json("POST", f"/sympheny-app/scenarios/{scenario_guid}/profiles-json", json=dump(request))
        envelope = ResponseDtoProfileResponseDto.model_validate(raw)
        return unwrap(envelope.data)

    def list(self, scenario_guid: str) -> list[ProfileResponseDto]:
        """List the profiles of a scenario. ``GET /sympheny-app/scenarios/{scenarioGuid}/profiles``"""
        raw = self._t.request_json("GET", f"/sympheny-app/scenarios/{scenario_guid}/profiles")
        envelope = ResponseDtoListProfileResponseDto.model_validate(raw)
        return unwrap(envelope.data)

    def get(self, scenario_guid: str, profile_id: int) -> ProfileDetailsResponseDto:
        """Get profile details. ``GET /sympheny-app/scenarios/{scenarioGuid}/profiles/{profileId}``"""
        raw = self._t.request_json("GET", f"/sympheny-app/scenarios/{scenario_guid}/profiles/{profile_id}")
        envelope = ResponseDtoProfileDetailsResponseDto.model_validate(raw)
        return unwrap(envelope.data)

    def update(self, scenario_guid: str, profile_id: int, request: ProfileRequestDtoPUT) -> ProfileDetailsResponseDto:
        """Update a profile. ``PUT /sympheny-app/v2/scenarios/{scenarioGuid}/profiles-json/{profileId}``"""
        raw = self._t.request_json("PUT", f"/sympheny-app/v2/scenarios/{scenario_guid}/profiles-json/{profile_id}", json=dump(request))
        envelope = ResponseDtoProfileDetailsResponseDto.model_validate(raw)
        return unwrap(envelope.data)

    def delete(self, scenario_guid: str, profile_id: int) -> None:
        """Delete a profile. ``DELETE /sympheny-app/scenarios/{scenarioGuid}/profiles/{profileId}``"""
        self._t.request_json("DELETE", f"/sympheny-app/scenarios/{scenario_guid}/profiles/{profile_id}")
