# Generated by scripts/generate_sync.py from sympheny_toolbox/_async/projects.py — do not edit by hand.
"""Project and analysis endpoints of the Sympheny platform API."""

from __future__ import annotations

from typing import TYPE_CHECKING

from sympheny_toolbox._envelope import dump, unwrap
from sympheny_toolbox.models import (
    AnalysisDetailsResponseDto,
    AnalysisRequestDto,
    AnalysisResponseDto,
    PagedResponseAnalysisResponseDto,
    ProjectDetailResponseDto,
    ProjectRequestDto,
    ProjectResponseDto,
    ProjectSummaryResponseDto,
    ResponseDtoAnalysisDetailsResponseDto,
    ResponseDtoAnalysisResponseDto,
    ResponseDtoProjectDetailResponseDto,
    ResponseDtoProjectResponseDto,
    ResponseDtoProjectSummaryResponseDto,
    ResponseDtoStatus,
    Status,
    Version,
)


if TYPE_CHECKING:
    from sympheny_toolbox._sync._transport import Transport


class Projects:
    """Operations on projects (``project-controller``)."""

    def __init__(self, transport: Transport) -> None:
        self._t = transport

    def list(self) -> list[ProjectResponseDto]:
        """List all projects visible to the authenticated user. ``GET /sympheny-app/projects``"""
        raw = self._t.request_json("GET", "/sympheny-app/projects")
        envelope = ResponseDtoProjectSummaryResponseDto.model_validate(raw)
        return unwrap(envelope.data).projects or []

    def create(self, request: ProjectRequestDto) -> ProjectResponseDto:
        """Create a new project. Only V2 projects are supported. ``POST /sympheny-app/projects``"""
        if request.version != Version.v2:
            raise ValueError("Only V2 projects are supported; set version=Version.v2")
        raw = self._t.request_json("POST", "/sympheny-app/projects", json=dump(request))
        envelope = ResponseDtoProjectResponseDto.model_validate(raw)
        return unwrap(envelope.data)

    def get(self, project_guid: str, *, include_analyses: bool | None = None) -> ProjectDetailResponseDto:
        """Get project details. ``GET /sympheny-app/projects/{guid}``"""
        params = {"includeAnalyses": include_analyses} if include_analyses is not None else None
        raw = self._t.request_json("GET", f"/sympheny-app/projects/{project_guid}", params=params)
        envelope = ResponseDtoProjectDetailResponseDto.model_validate(raw)
        return unwrap(envelope.data)

    def delete(self, project_guid: str) -> ProjectSummaryResponseDto:
        """Delete a project; returns the remaining projects. ``DELETE /sympheny-app/projects/{guid}``"""
        raw = self._t.request_json("DELETE", f"/sympheny-app/projects/{project_guid}")
        envelope = ResponseDtoProjectSummaryResponseDto.model_validate(raw)
        return unwrap(envelope.data)


class Analyses:
    """Operations on analyses (``analysis-controller``)."""

    def __init__(self, transport: Transport) -> None:
        self._t = transport

    def list(self, project_guid: str) -> list[AnalysisResponseDto]:
        """List the analyses of a project. ``GET /sympheny-app/projects/{guid}/analyses``"""
        raw = self._t.request_json("GET", f"/sympheny-app/projects/{project_guid}/analyses")
        envelope = PagedResponseAnalysisResponseDto.model_validate(raw)
        return unwrap(envelope.data)

    def create(self, project_guid: str, request: AnalysisRequestDto) -> AnalysisResponseDto:
        """Create a new analysis in a project. ``POST /sympheny-app/projects/{guid}/analyses``"""
        raw = self._t.request_json("POST", f"/sympheny-app/projects/{project_guid}/analyses", json=dump(request))
        envelope = ResponseDtoAnalysisResponseDto.model_validate(raw)
        return unwrap(envelope.data)

    def get(self, project_guid: str, analysis_guid: str) -> AnalysisDetailsResponseDto:
        """Get analysis details. ``GET /sympheny-app/projects/{guid}/analysis/{analysisGuid}``"""
        raw = self._t.request_json("GET", f"/sympheny-app/projects/{project_guid}/analysis/{analysis_guid}")
        envelope = ResponseDtoAnalysisDetailsResponseDto.model_validate(raw)
        return unwrap(envelope.data)

    def delete(self, analysis_guid: str) -> Status:
        """Delete an analysis. ``DELETE /sympheny-app/analysis/{analysisGuid}``

        The API returns no ``data`` payload for this endpoint even on success, so a missing
        payload is treated as an empty :class:`Status` rather than an error.
        """
        raw = self._t.request_json("DELETE", f"/sympheny-app/analysis/{analysis_guid}")
        envelope = ResponseDtoStatus.model_validate(raw)
        return envelope.data if envelope.data is not None else Status()
