# Generated by scripts/generate_sync.py from sympheny_toolbox/_async/stages.py — do not edit by hand.
"""Operations on stages of the Sympheny platform API (``stage-controller``)."""

from __future__ import annotations

from typing import TYPE_CHECKING

from sympheny_toolbox._envelope import dump, unwrap
from sympheny_toolbox.models import (
    ResponseDtoListStageResponseDto,
    ResponseDtoStageResponseDto,
    StageCore,
    StageRequestDto,
    StageResponseDto,
)


if TYPE_CHECKING:
    from sympheny_toolbox._sync._transport import Transport


class Stages:
    """Operations on stages (``stage-controller``)."""

    def __init__(self, transport: Transport) -> None:
        self._t = transport

    def list(self, scenario_guid: str) -> list[StageResponseDto]:
        """List the stages of a scenario. ``GET /sympheny-app/scenarios/{scenarioGuid}/stages``"""
        raw = self._t.request_json("GET", f"/sympheny-app/scenarios/{scenario_guid}/stages")
        envelope = ResponseDtoListStageResponseDto.model_validate(raw)
        return unwrap(envelope.data)

    def create(self, scenario_guid: str, request: StageRequestDto) -> StageResponseDto:
        """Create a new stage in a scenario. ``POST /sympheny-app/scenarios/{scenarioGuid}/stages``"""
        raw = self._t.request_json("POST", f"/sympheny-app/scenarios/{scenario_guid}/stages", json=dump(request))
        envelope = ResponseDtoStageResponseDto.model_validate(raw)
        return unwrap(envelope.data)

    def get(self, stage_guid: str) -> StageResponseDto:
        """Get stage details. ``GET /sympheny-app/scenarios/stages/{guid}``"""
        raw = self._t.request_json("GET", f"/sympheny-app/scenarios/stages/{stage_guid}")
        envelope = ResponseDtoStageResponseDto.model_validate(raw)
        return unwrap(envelope.data)

    def update(self, scenario_guid: str, stage_guid: str, request: StageCore) -> StageResponseDto:
        """Update a stage. ``PUT /sympheny-app/scenarios/{scenarioGuid}/stages/{stageGuid}``"""
        raw = self._t.request_json("PUT", f"/sympheny-app/scenarios/{scenario_guid}/stages/{stage_guid}", json=dump(request))
        envelope = ResponseDtoStageResponseDto.model_validate(raw)
        return unwrap(envelope.data)

    def delete(self, scenario_guid: str, stage_guid: str) -> None:
        """Delete a stage. ``DELETE /sympheny-app/scenarios/{scenarioGuid}/stages/{stageGuid}``"""
        self._t.request_json("DELETE", f"/sympheny-app/scenarios/{scenario_guid}/stages/{stage_guid}")
