# Generated by scripts/generate_sync.py from sympheny_toolbox/_async/storage_technologies.py — do not edit by hand.
"""Operations on storage technologies of the Sympheny platform API (``storage-technology-controller``)."""

from __future__ import annotations

from typing import TYPE_CHECKING

from sympheny_toolbox._envelope import dump, unwrap
from sympheny_toolbox.models import (
    ResponseDtoStorageTechnologyDetailResponseDtoV2,
    ResponseDtoStorageTechnologyListResponseDto,
    ResponseDtoStorageTechnologyListResponseDtoV2,
    ResponseDtoStorageTechnologyResponseDtoV2,
    StorageTechnologyDetailResponseDtoV2,
    StorageTechnologyListResponseDto,
    StorageTechnologyListResponseDtoV2,
    StorageTechnologyRequestDtoPUT,
    StorageTechnologyRequestDtoV2,
    StorageTechnologyResponseDtoV2,
)


if TYPE_CHECKING:
    from sympheny_toolbox._sync._transport import Transport


class StorageTechnologies:
    """Operations on storage technologies (``storage-technology-controller``)."""

    def __init__(self, transport: Transport) -> None:
        self._t = transport

    def create(self, scenario_guid: str, request: StorageTechnologyRequestDtoV2) -> StorageTechnologyResponseDtoV2:
        """Create a storage technology in a scenario. ``POST /sympheny-app/v2_1/scenarios/{scenarioGuid}/storage-technologies``"""
        raw = self._t.request_json("POST", f"/sympheny-app/v2_1/scenarios/{scenario_guid}/storage-technologies", json=dump(request))
        envelope = ResponseDtoStorageTechnologyResponseDtoV2.model_validate(raw)
        return unwrap(envelope.data)

    def list(self, scenario_guid: str) -> StorageTechnologyListResponseDtoV2:
        """List the storage technologies of a scenario. ``GET /sympheny-app/v2/scenarios/{scenarioGuid}/storage-technologies``"""
        raw = self._t.request_json("GET", f"/sympheny-app/v2/scenarios/{scenario_guid}/storage-technologies")
        envelope = ResponseDtoStorageTechnologyListResponseDtoV2.model_validate(raw)
        return unwrap(envelope.data)

    def get(self, technology_guid: str) -> StorageTechnologyDetailResponseDtoV2:
        """Get storage technology details. ``GET /sympheny-app/v2/scenarios/storage-technologies/{guid}``"""
        raw = self._t.request_json("GET", f"/sympheny-app/v2/scenarios/storage-technologies/{technology_guid}")
        envelope = ResponseDtoStorageTechnologyDetailResponseDtoV2.model_validate(raw)
        return unwrap(envelope.data)

    def update(self, technology_guid: str, request: StorageTechnologyRequestDtoPUT) -> StorageTechnologyDetailResponseDtoV2:
        """Update a storage technology. ``PUT /sympheny-app/v2_2/scenarios/storage-technologies/{guid}``"""
        raw = self._t.request_json("PUT", f"/sympheny-app/v2_2/scenarios/storage-technologies/{technology_guid}", json=dump(request))
        envelope = ResponseDtoStorageTechnologyDetailResponseDtoV2.model_validate(raw)
        return unwrap(envelope.data)

    def delete(self, technology_guid: str) -> StorageTechnologyListResponseDto:
        """Delete a storage technology; returns the remaining storage technologies. ``DELETE /sympheny-app/scenarios/storage-technologies/{guid}``"""
        raw = self._t.request_json("DELETE", f"/sympheny-app/scenarios/storage-technologies/{technology_guid}")
        envelope = ResponseDtoStorageTechnologyListResponseDto.model_validate(raw)
        return unwrap(envelope.data)
