# Generated by scripts/generate_sync.py from sympheny_toolbox/_async/users.py — do not edit by hand.
"""Operations on user accounts of the Sympheny backoffice API (``External Users``)."""

from __future__ import annotations

from typing import TYPE_CHECKING

from sympheny_toolbox.models import GetUserProfileExt


if TYPE_CHECKING:
    from sympheny_toolbox._sync._transport import Transport


class Users:
    """User account endpoints (``External Users``)."""

    def __init__(self, transport: Transport) -> None:
        self._t = transport

    def profile(self) -> GetUserProfileExt:
        """Get the profile of the authenticated user. ``GET /backoffice/ext/users/profile``"""
        raw = self._t.request_json("GET", "/backoffice/ext/users/profile")
        return GetUserProfileExt.model_validate(raw)
