"""Generate the synchronous client from the asynchronous source of truth.

Transforms every module in ``src/sympheny_toolbox/_async/`` into its synchronous
counterpart in ``src/sympheny_toolbox/_sync/`` (unasync-style token replacement).
The ``_async`` package is hand-written; the ``_sync`` package is generated and
must never be edited by hand.

Usage:
    uv run python scripts/generate_sync.py          # (re)generate
    uv run python scripts/generate_sync.py --check  # fail if _sync/ is out of date
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
ASYNC_DIR = REPO_ROOT / "src" / "sympheny_toolbox" / "_async"
SYNC_DIR = REPO_ROOT / "src" / "sympheny_toolbox" / "_sync"

HEADER = "# Generated by scripts/generate_sync.py from sympheny_toolbox/_async/{name} — do not edit by hand.\n"

# Ordered token replacements. Longer/more specific patterns first.
REPLACEMENTS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"sympheny_toolbox\._async"), "sympheny_toolbox._sync"),
    (re.compile(r"httpx\.AsyncClient"), "httpx.Client"),
    (re.compile(r"\basync def "), "def "),
    (re.compile(r"\basync with "), "with "),
    (re.compile(r"\basync for "), "for "),
    (re.compile(r"\bawait "), ""),
    (re.compile(r"\baclose\b"), "close"),
    (re.compile(r"\b__aenter__\b"), "__enter__"),
    (re.compile(r"\b__aexit__\b"), "__exit__"),
    (re.compile(r"\bAsync([A-Z]\w*)"), r"\1"),
    (re.compile(r"\basynchronous\b"), "synchronous"),
]


def transform(source: str) -> str:
    for pattern, replacement in REPLACEMENTS:
        source = pattern.sub(replacement, source)
    return source


def generate(target_dir: Path) -> list[Path]:
    """Transform all async modules into ``target_dir``, format them, and return the file list."""
    async_files = sorted(ASYNC_DIR.glob("*.py"))
    if not async_files:
        sys.exit(f"No source files found in {ASYNC_DIR}")
    target_dir.mkdir(exist_ok=True)

    targets = []
    for path in async_files:
        target = target_dir / path.name
        target.write_text(HEADER.format(name=path.name) + transform(path.read_text()))
        targets.append(target)
    # Removing `await ` can shorten lines below the length limit, so re-format the output.
    subprocess.run(["uv", "run", "ruff", "format", "--quiet", *map(str, targets)], cwd=REPO_ROOT, check=True)  # noqa: S603, S607
    return targets


def main() -> None:
    check_only = "--check" in sys.argv[1:]

    if check_only:
        with tempfile.TemporaryDirectory() as tmp:
            generated = generate(Path(tmp))
            expected_names = {f.name for f in generated}
            stale = [f.name for f in generated if not (SYNC_DIR / f.name).exists() or (SYNC_DIR / f.name).read_text() != f.read_text()]
            stale += [f.name for f in SYNC_DIR.glob("*.py") if f.name not in expected_names]
        if stale:
            print("Out-of-date generated files (run: uv run python scripts/generate_sync.py):")
            print("\n".join(f"  src/sympheny_toolbox/_sync/{name}" for name in sorted(stale)))
            sys.exit(1)
        print("_sync/ is up to date")
        return

    if SYNC_DIR.exists():
        shutil.rmtree(SYNC_DIR)
    generated = generate(SYNC_DIR)
    print(f"Generated {len(generated)} files into src/sympheny_toolbox/_sync/")


if __name__ == "__main__":
    main()
